import {characters} from '../data/characters';
import {statsFor,grantXP,refreshPeriods} from './progression';
import {progression} from '../data/unlocks';
import {statKeys,type Stats,type Stat,type Difficulty,type Mode,type Save} from '../types';
export function compare(a:number,b:number){return a===b?'draw':a>b?'player':'ai';}
export function aiStat(own:Stats,difficulty:Difficulty,rng=Math.random):Stat {if(difficulty==='Easy'||(difficulty==='Normal'&&rng()<.35))return statKeys[Math.floor(rng()*statKeys.length)];const averages=Object.fromEntries(statKeys.map(k=>[k,characters.reduce((n,c)=>n+c.baseStats[k],0)/characters.length])) as Stats;return [...statKeys].sort((a,b)=>(own[b]-(difficulty==='Expert'?averages[b]:0))-(own[a]-(difficulty==='Expert'?averages[a]:0)))[0];}
export interface Battle {mode:Mode;difficulty:Difficulty;target:number;player:string[];ai:string[];pot:string[];turn:'player'|'ai';round:number;scores:[number,number];result?:'player'|'ai'|'draw';last?:{stat:Stat;a:number;b:number;winner:string};log:string[];strengthWins:number;participants:string[];tutorial:boolean}
export function createBattle(ids:string[],mode:Mode,difficulty:Difficulty,target=5,tutorial=false):Battle {const shuffled=[...characters].sort(()=>Math.random()-.5);const opponents=(mode==='Crossover Battle'?shuffled.filter(c=>!ids.some(id=>characters.find(x=>x.id===id)?.franchise===c.franchise)):shuffled).slice(0,ids.length).map(c=>c.id);return {mode,difficulty,target,player:[...ids],ai:opponents,pot:[],turn:'player',round:0,scores:[0,0],log:[],strengthWins:0,participants:ids,tutorial};}
export function playRound(b:Battle,stat:Stat,s:Save):Battle {if(b.result)return b;const next=structuredClone(b);const p=characters.find(c=>c.id===b.player[0])!,a=characters.find(c=>c.id===b.ai[0])!;const ps=statsFor(p,s),as=a.baseStats;const winner=compare(ps[stat],as[stat]);next.round++;next.last={stat,a:ps[stat],b:as[stat],winner};next.log.unshift(`${p.name} ${ps[stat]} · ${a.name} ${as[stat]} — ${stat}: ${winner==='draw'?'tie':winner==='player'?'you win':'opponent wins'}`);if(winner!=='draw'){next.scores[winner==='player'?0:1]++;next.turn=winner;if(winner==='player'&&stat==='strength')next.strengthWins++;}
if(b.mode==='Classic'){const pair=[next.player.shift()!,next.ai.shift()!];if(winner==='draw')next.pot.push(...pair);else {next[winner].push(...next.pot,...pair);next.pot=[];}if(!next.player.length||!next.ai.length){if(winner==='draw'&&next.pot.length){next.player.push(...next.pot.filter((_,i)=>i%2===0));next.ai.push(...next.pot.filter((_,i)=>i%2===1));next.pot=[];}else next.result=next.player.length?'player':'ai';}if(next.round>=150&&!next.result)next.result=next.player.length===next.ai.length?'draw':next.player.length>next.ai.length?'player':'ai';}
else {next.player.push(next.player.shift()!);next.ai.push(next.ai.shift()!);const limit=b.mode==='Quick Battle'?3:b.mode==='Team Battle'?b.participants.length:b.target;if(next.round>=limit||((b.mode==='Best of'||b.mode==='Quick Battle')&&Math.max(...next.scores)>limit/2))next.result=next.scores[0]===next.scores[1]?'draw':next.scores[0]>next.scores[1]?'player':'ai';}return next;}
export function rewardMatch(s:Save,b:Battle){if(!b.result)return s;refreshPeriods(s);const won=b.result==='player';if(won){s.wins++;s.periods.dailyWins++;s.periods.weeklyWins++;if(b.scores[1]===0)s.perfectWins++;new Set(b.participants.map(id=>characters.find(c=>c.id===id)!.franchise)).forEach(f=>s.franchiseWins[f]=(s.franchiseWins[f]||0)+1);}else if(b.result==='ai')s.losses++;s.roundWins+=b.scores[0];s.strengthWins+=b.strengthWins;s.coins+=won?progression.winCoins:progression.lossCoins;s.materials+=won?2:1;b.participants.forEach(id=>{const p=s.cards[id];if(p){p.xp+=won?40:20;p.wins+=won?1:0;}});s.history.unshift({date:new Date().toISOString(),mode:b.mode,won,score:b.scores.join(' : ')});s.history=s.history.slice(0,30);return grantXP(s,won?progression.matchXP:progression.lossXP);}
