import {useState} from 'react';
import {Search} from 'lucide-react';
import {characters} from '../data/characters';
import {franchises} from '../data/franchises';
import {groups} from '../data/groups';
import {rarities} from '../data/rarities';
import {powerFor} from '../game/progression';
import {Card} from '../components/Card';
import type {Save} from '../types';
export function Collection({save,detail,initial=''}:{save:Save;detail:(id:string)=>void;initial?:string}){const [search,setSearch]=useState(''),[franchise,setFranchise]=useState(initial),[rarity,setRarity]=useState(''),[group,setGroup]=useState(''),[level,setLevel]=useState(''),[sort,setSort]=useState('power'),[owned,setOwned]=useState(false),[favourites,setFavourites]=useState(false);const list=characters.filter(c=>(!franchise||c.franchise===franchise)&&(!rarity||c.rarity===rarity)&&(!group||c.group===group)&&(!level||(save.cards[c.id]?.level||1)>=Number(level))&&(!owned||save.owned.includes(c.id))&&(!favourites||save.favourite===c.id)&&c.name.toLowerCase().includes(search.toLowerCase())).sort((a,b)=>sort==='name'?a.name.localeCompare(b.name):powerFor(b,save)-powerFor(a,save));return <><div className="page-heading"><div><span className="eyebrow">BUILD YOUR LEGACY</span><h1>My collection <em>{save.owned.length}/32</em></h1><p>Meet your legends. Discover your next obsession.</p></div></div><div className="filters"><label className="search"><Search size={18}/><input aria-label="Search characters" placeholder="Search your multiverse…" value={search} onChange={e=>setSearch(e.target.value)}/></label><select aria-label="Universe filter" value={franchise} onChange={e=>setFranchise(e.target.value)}><option value="">All universes</option>{franchises.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select><select aria-label="Rarity filter" value={rarity} onChange={e=>setRarity(e.target.value)}><option value="">All rarities</option>{Object.keys(rarities).map(r=><option key={r}>{r}</option>)}</select><select aria-label="Group filter" value={group} onChange={e=>setGroup(e.target.value)}><option value="">All groups</option>{groups.map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select><select aria-label="Minimum level" value={level} onChange={e=>setLevel(e.target.value)}><option value="">Any level</option>{[5,10,20].map(n=><option key={n} value={n}>Level {n}+</option>)}</select><select aria-label="Sort cards" value={sort} onChange={e=>setSort(e.target.value)}><option value="power">Power: highest first</option><option value="name">Name: A–Z</option></select><label><input type="checkbox" checked={owned} onChange={e=>setOwned(e.target.checked)}/> Owned only</label><label><input type="checkbox" checked={favourites} onChange={e=>setFavourites(e.target.checked)}/> Favourite</label></div><div className="collection-grid">{list.map(c=><Card key={c.id} character={c} save={save} locked={!save.owned.includes(c.id)} onClick={()=>detail(c.id)}/>)}</div>{!list.length&&<div className="empty">No cards match. Try changing your filters.</div>}</>;}
